/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CensorOptions {
  customChar?: string
  keepFirstLast?: boolean
  matchWholeWord?: boolean
  ignoreList?: Array<string>
}
export interface MatchResult {
  word: string
  matchText: string
  start: number
  end: number
}
export declare class TextCensor {
  constructor(words: Array<string>)
  clean(text: string): string
  cleanCustom(text: string, options: CensorOptions): string
  getMatches(text: string, options?: CensorOptions | undefined | null): Array<MatchResult>
  cleanAsync(text: string): Promise<string>
  cleanCustomAsync(text: string, options: CensorOptions): Promise<string>
  addWords(words: Array<string>): void
}
