/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class TextCensor {
  constructor(words: Array<string>)
  clean(text: string): string
  addWords(words: Array<string>): void
}
